# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import datasets
import sklearn.model_selection as ms

import numpy as np

Переписать, используя model_selection

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
train_data, test_data, train_labels, test_labels = ms.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [4]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [5]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [6]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 6.1  3.   4.9  1.8]
 [ 5.7  2.9  4.2  1.3]
 [ 5.4  3.4  1.7  0.2]
 [ 6.3  2.8  5.1  1.5]
 [ 7.4  2.8  6.1  1.9]]


Тестовая выборка:
[[ 6.2  2.2  4.5  1.5]
 [ 6.3  2.5  5.   1.9]
 [ 5.2  4.1  1.5  0.1]
 [ 6.4  3.2  5.3  2.3]
 [ 4.8  3.   1.4  0.3]]


In [7]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[2 1 0 2 2 0 0 2 1 1 2 0 2 1 1 2 1 1 1 1 1 1 1 0 0 0 1 1 2 1 0 1 2 0 1 0 0
 2 2 1 1 1 0 2 0 2 0 0 0 1 0 0 2 1 0 1 0 1 2 1 2 1 0 1 1 1 0 1 1 2 2 0 2 0
 1 1 0 0 0 2 2 1 1 0 0 1 2 2 0 2 0 0 0 2 0 2 0 2 2 1 2 2 0 2 2]


Метки классов на тестовой выборке:
[1 2 0 2 0 1 0 2 2 0 2 1 2 0 1 2 2 0 1 2 0 1 1 0 1 0 0 1 2 0 1 1 1 2 2 0 0
 2 2 2 2 1 2 2 0]


### Стратегии проведения кросс-валидации

#### KFold

In [8]:
for train_indexes, test_indexes in ms.KFold(n_splits=5).split(np.arange(10)):
    print train_indexes, test_indexes

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [9]:
#многократный запуск приводит к различным разбиениям
for train_indices, test_indices in ms.KFold(n_splits = 2, shuffle = True).split(np.arange(10)):
    print train_indices, test_indices

[1 2 6 7 9] [0 3 4 5 8]
[0 3 4 5 8] [1 2 6 7 9]


In [10]:
#многократный запуск приводит к одному и  тому же разбиению, результат запуска детерминированный
for train_indices, test_indices in ms.KFold(n_splits = 2, shuffle = True, random_state = 1).split(np.arange(10)):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [11]:
target = np.array([0] * 5 + [1] * 5)
print target
kf =  ms.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in kf.split(np.arange(len(target)), target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [12]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in ms.StratifiedKFold(n_splits = 2,shuffle = True).split(np.arange(len(target)), target):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[4 5 8 9] [0 1 2 3 6 7]
[0 1 2 3 6 7] [4 5 8 9]


#### ShuffleSplit

In [13]:
for train_indices, test_indices in ms.ShuffleSplit(n_splits = 4, test_size = 0.2).split(np.arange(10)):
    print train_indices, test_indices

[5 2 4 9 7 8 0 3] [6 1]
[0 8 2 5 6 7 4 9] [3 1]
[2 6 3 0 5 9 1 7] [4 8]
[5 2 6 8 3 1 9 7] [4 0]


#### StratifiedShuffleSplit

In [14]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]


NameError: name 'cross_validation' is not defined

In [15]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in ms.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2).split(np.arange(len(target)), target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[1 5 8 3 4 9 6 2] [7 0]
[9 7 4 3 5 2 8 0] [6 1]
[4 8 6 3 2 7 5 1] [9 0]
[5 0 9 8 3 4 1 6] [2 7]


#### Leave-One-Out

In [16]:
for train_indices, test_index in ms.LeaveOneOut().split(np.arange(10)):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators

Видимо StratifiedShuffleSplit просто не заметил