# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [57]:
from sklearn import datasets
import sklearn.model_selection as ms

import numpy as np

Переписать, используя model_selection

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [16]:
iris = datasets.load_iris()

In [17]:
train_data, test_data, train_labels, test_labels = ms.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [5]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [6]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [7]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 4.6  3.2  1.4  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.7  2.8  4.1  1.3]
 [ 5.6  2.9  3.6  1.3]
 [ 5.6  2.8  4.9  2. ]]


Тестовая выборка:
[[ 4.5  2.3  1.3  0.3]
 [ 6.5  2.8  4.6  1.5]
 [ 5.6  3.   4.5  1.5]
 [ 4.4  2.9  1.4  0.2]
 [ 5.8  2.8  5.1  2.4]]


In [9]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[0 0 1 1 2 0 0 0 0 2 2 2 1 1 1 2 0 1 2 2 1 2 0 1 2 0 1 2 0 2 2 2 0 0 1 0 2
 2 2 1 0 0 2 1 0 2 1 2 2 2 1 1 0 1 2 2 1 1 1 2 1 2 0 2 2 2 1 2 0 0 1 0 2 0
 0 1 1 1 2 2 2 1 2 2 0 1 2 1 1 0 0 2 0 1 2 0 2 0 2 2 0 1 0 1 2]


Метки классов на тестовой выборке:
[0 1 1 0 2 0 2 2 1 2 1 1 0 0 0 1 0 1 1 0 2 2 1 1 1 0 1 0 0 2 1 0 0 1 0 0 2
 0 0 1 1 1 0 1 0]


### Стратегии проведения кросс-валидации

#### KFold

In [28]:
for train_indexes, test_indexes in ms.KFold(n_splits=5).split(np.arange(10)):
    print train_indexes, test_indexes

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [29]:
#многократный запуск приводит к различным разбиениям
for train_indices, test_indices in ms.KFold(n_splits = 2, shuffle = True).split(np.arange(10)):
    print train_indices, test_indices

[1 4 5 6 9] [0 2 3 7 8]
[0 2 3 7 8] [1 4 5 6 9]


In [30]:
#многократный запуск приводит к одному и  тому же разбиению, результат запуска детерминированный
for train_indices, test_indices in ms.KFold(n_splits = 2, shuffle = True, random_state = 1).split(np.arange(10)):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [36]:
target = np.array([0] * 5 + [1] * 5)
print target
kf =  ms.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in kf.split(np.arange(len(target)), target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [40]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in ms.StratifiedKFold(n_splits = 2,shuffle = True).split(np.arange(len(target)), target):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[0 1 4 5] [2 3 6 7 8 9]
[2 3 6 7 8 9] [0 1 4 5]


#### ShuffleSplit

In [53]:
for train_indices, test_indices in ms.ShuffleSplit(n_splits = 4, test_size = 0.2).split(np.arange(10)):
    print train_indices, test_indices

[2 5 6 0 1 3 8 4] [9 7]
[2 6 9 3 1 7 0 8] [4 5]
[0 5 7 8 3 2 4 9] [1 6]
[8 6 2 1 4 5 3 9] [7 0]


#### StratifiedShuffleSplit

In [14]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 9 5 0 8 7 1 4] [2 6]
[3 7 0 9 4 1 5 8] [2 6]
[8 3 9 0 1 5 4 6] [2 7]
[8 4 1 9 2 5 0 7] [3 6]


In [54]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in ms.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2).split(np.arange(len(target)), target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[0 5 3 9 4 1 7 8] [6 2]
[3 9 0 5 4 8 6 2] [7 1]
[4 8 5 7 0 1 6 2] [9 3]
[4 7 0 1 9 5 6 2] [3 8]


#### Leave-One-Out

In [56]:
for train_indices, test_index in ms.LeaveOneOut().split(np.arange(10)):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators