In [1]:
import numpy as np

In [9]:
input = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

In [10]:
input

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
W = np.array([1, 4, 8, 8, 2, 2, 8, 0, 0]).reshape(3, 3)

In [14]:
input.reshape([input.shape[0], -1]).dot(W)

array([[41,  8, 12],
       [92, 26, 42]])

In [15]:
input.dot(W)

array([[41,  8, 12],
       [92, 26, 42]])

In [19]:
(input.dot(W)).reshape(input.shape[0], -1)

array([[41,  8, 12],
       [92, 26, 42]])