# Demand prediction baseline solution

Victor Kantor, xead.wl@gmail.com

In [131]:
import pandas as pd
from copy import deepcopy

train = pd.read_csv("train.tsv")
test = pd.read_csv("test.tsv")
sample_submission = pd.read_csv("sample_submission.tsv")

In [20]:
unchanged_train = deepcopy(train)

In [21]:
Y_table = train[['Num', 'y', 'year', 'week', 'item_id']]

In [22]:
results = []

In [23]:
import sklearn.model_selection as ms
import numpy as np

In [24]:
def SMAPE(X, Y):
    np.abs(X - Y) / ((np.abs(X) + np.abs(Y))/2) / X.shape

In [25]:
train_sample = train.sample(frac=0.1, random_state=42)
target_sample = train_sample[['Num', 'y', 'year', 'week']]

In [26]:
def transform(data):
    for i, row in data.iterrows():
        shift = row['shift']
        if 1 <= row['week'] - shift <= 52:
            data.set_value(i, 'week', row['week'] - shift)
        else:
            if (row['year'] == 2015):
                data.set_value(i, 'week', 53 + (row['week'] - shift))
            else:
                data.set_value(i, 'week', 52 + (row['week'] - shift))
            data.set_value(i, 'year', row['year'] - 1)

In [27]:
transform(train)

In [28]:
train.drop(['shift', 'Num', 'y'], axis=1, inplace=True)

In [29]:
train = train.drop_duplicates()

In [30]:
Y_table = unchanged_train[['y', 'year', 'week', 'item_id']]

In [31]:
merged_table = pd.merge(train, Y_table, how='right', on=['year', 'week', 'item_id'])

In [98]:
merged_table = merged_table.dropna()
merged_table = merged_table.drop_duplicates()

In [99]:
X = merged_table.drop(['y'], axis=1)
Y = merged_table['y']

In [100]:
estimator = XGBRegressor(max_depth=15, learning_rate=0.1, n_estimators=500, nthread=2, seed=41)

In [101]:
result = ms.cross_val_score(estimator, X, Y, scoring=smape_score)
print result.mean()

0.00207918900792


In [102]:
sliced = merged_table.sample(frac=0.1,random_state=41)

In [103]:
X = sliced.drop(['y'], axis=1)
Y = sliced['y']

In [104]:
len(X), len(Y)

(2400, 2400)

In [127]:
estimator = XGBRegressor(max_depth=6, learning_rate=0.1, n_estimators=100, nthread=2, seed=41)

In [123]:
result = ms.cross_val_score(estimator, X, Y, scoring=smape_score)
print result.mean()

0.0659097123969


In [124]:
x_tr = X[:1200]
y_tr = Y[:1200]
x_te = X[1200:]
y_te = Y[1200:]

In [125]:
estimator.fit(x_tr, y_tr)

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=None, n_estimators=100, nthread=2,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=41, silent=True, subsample=1)

In [126]:
smape100(estimator, x_te, y_te)

7.0538393054876041

In [50]:
my_test = merged_table.sample(frac=0.1,random_state=69)

In [51]:
X_test = sliced.drop(['y'], axis=1)
Y_test = sliced['y']

In [52]:
estimator.fit(X, Y)

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=15,
       min_child_weight=1, missing=None, n_estimators=500, nthread=2,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=41, silent=True, subsample=1)

In [53]:
smape_score(estimator, X_test, Y_test)

8.463224339044106e-05

24860

In [142]:
test = merged_table[-10000:]

In [143]:
tr = merged_table[:10000]

In [144]:
X_train = tr.drop(['y'], axis=1)
Y_train = tr['y']

In [145]:
X_test = test.drop(['y'], axis=1)
Y_test = test['y']

In [146]:
estimator = XGBRegressor(max_depth=5, learning_rate=0.1, n_estimators=100, nthread=2, seed=41)

In [147]:
estimator.fit(X_train, Y_train)

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=100, nthread=2,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=41, silent=True, subsample=1)

In [149]:
smape100(estimator, X_test, Y_test)

7.2642676146612093

In [92]:
pred = estimator.predict(X_test)

In [93]:
pred

array([  3.55581500e+05,   2.41594214e+03,   1.82036547e+05, ...,
         6.17417578e+03,   2.80995209e+02,   8.28707703e+02], dtype=float32)

In [96]:
def smape100(estimator, X, Y):
    pred = estimator.predict(X)
    return 100 * np.sum(2 * np.abs(pred - Y) / (np.abs(pred) + np.abs(Y)))/len(pred)

In [97]:
print smape100(estimator, X_test, Y_test)

0.260876248762


In [155]:
X = merged_table.drop(['y'], axis=1)[:5000]
Y = merged_table['y'][:5000]

In [156]:
SUPER_HYDRA_NAGIBATOR_1337_POCAN = XGBRegressor(max_depth=5,
                                                learning_rate=0.1,
                                                n_estimators=100,
                                                nthread=2,
                                                seed=41)

In [157]:
SUPER_HYDRA_NAGIBATOR_1337_POCAN.fit(X, Y)

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=5,
       min_child_weight=1, missing=None, n_estimators=100, nthread=2,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=41, silent=True, subsample=1)

In [427]:
ms.cross_val_score(SUPER_HYDRA_NAGIBATOR_1337_POCAN, X, Y, scoring=smape_score)

array([ 0.00603156,  0.00548405,  0.00663336])

In [165]:
test = pd.read_csv("test.tsv")
sample_submission = pd.read_csv("sample_submission.tsv")

In [166]:
test

Num  year  week  shift   item_id        f1        f2        f3  \
0     348622  2015     3      3  20447918     960.0     820.0    1128.0   
1     348623  2015     3      3  20447902    9086.0   12585.0   11595.0   
2     348624  2015     3      3  20447732  115087.0  147287.0  176065.0   
3     348625  2015     3      3  20443951   20900.0   24420.0   27068.0   
4     348626  2015     3      3  20443944    4430.0    5864.0    3310.0   
5     348627  2015     3      3  20443943   57289.0   80036.0  112511.0   
6     348628  2015     3      3  20443941   21868.0   30620.0   45886.0   
7     348629  2015     3      3  20443902   41105.0   57637.0   54540.0   
8     348630  2015     3      3  20443901   39381.0   56933.0   59899.0   
9     348631  2015     3      3  20443308    5922.0   16070.0   14665.0   
10    348632  2015     3      3  20443307    5120.0    9280.0    9015.0   
11    348633  2015     3      3  20443057   52035.0   64435.0   63748.0   
12    348634  2015     3      3  20443056  260820.0  313213.0  309797.0   
13    348635  2015     3      3  20443055   39965.0   52095.0   45319.0   
14    348636  2015     3      3  20447919    1390.0    1330.0    2038.0   
15    348637  2015     3      3  20447972  151240.0  205018.0  222380.0   
16    348638  2015     3      3  20447973   90680.0  121015.0  136680.0   
17    348639  2015     3      3  20448083  349524.0  427399.0  447686.0   
18    348640  2015     3      3  20448084  356664.0  434893.0  456498.0   
19    348641  2015     3      3  20448086    1610.0    1980.0    2500.0   
20    348642  2015     3      3  20448095   96366.0  124304.0  126985.0   
21    348643  2015     3      3  20448162   49250.0   72969.0   63869.0   
22    348644  2015     3      3  20448312     860.0     880.0    1070.0   
23    348645  2015     3      3  20448455   11546.0   15598.0   15334.0   
24    348646  2015     3      3  20448467    6473.0    7353.0    9471.0   
25    348647  2015     3      3  20448805  110907.0  143261.0  141189.0   
26    348648  2015     3      3  20448900    5620.0    9982.0   10559.0   
27    348649  2015     3      3  20448958   35225.0   64345.0   77183.0   
28    348650  2015     3      3  20441997    9695.0   13490.0   12850.0   
29    348651  2015     3      3  20441382   13490.0   19755.0   17685.0   
...      ...   ...   ...    ...       ...       ...       ...       ...   
1986  351499  2015     5      1  20441131    9190.0   10080.0   10215.0   
1987  351500  2015     5      1  20441187  211593.0  228546.0  227395.0   
1988  351501  2015     5      1  20441372   10990.0   10580.0    9255.0   
1989  351502  2015     5      1  20438683   23590.0   20395.0   19040.0   
1990  351503  2015     5      1  20438923    2360.0    2040.0    2540.0   
1991  351504  2015     5      1  20438941     565.0     890.0     815.0   
1992  351505  2015     5      1  20438686   15500.0   14785.0   14760.0   
1993  351506  2015     5      1  20438690     430.0     595.0     615.0   
1994  351507  2015     5      1  20438691     100.0      40.0      70.0   
1995  351508  2015     5      1  20438693  101345.0  101553.0  107065.0   
1996  351509  2015     5      1  20438694  597449.0  587464.0  586763.0   
1997  351510  2015     5      1  20438702  266010.0  240524.0  253241.0   
1998  351511  2015     5      1  20438703  574490.0  497758.0  544345.0   
1999  351512  2015     5      1  20438704   21319.0   21825.0   21803.0   
2000  351513  2015     5      1  20438705    6805.0    6330.0    5870.0   
2001  351514  2015     5      1  20438706   24840.0   26430.0   25860.0   
2002  351515  2015     5      1  20438710  457442.0  409176.0  434183.0   
2003  351516  2015     5      1  20438711  106051.0  114452.0   99345.0   
2004  351517  2015     5      1  20438716  197118.0  209311.0  210250.0   
2005  351518  2015     5      1  20438715  528162.0  510066.0  535224.0   
2006  351519  2015     5      1  20438922     810.0     790.0     765.0   
2007  351520  2015     5      1  2

In [167]:
transform(test)

In [168]:
test.drop('shift', axis=1, inplace=True)

In [169]:
test.drop('Num', axis=1, inplace=True)

In [170]:
test

year  week   item_id        f1        f2        f3        f4        f5  \
0     2014    53  20447918     960.0     820.0    1128.0    1801.0    1045.0   
1     2014    53  20447902    9086.0   12585.0   11595.0    9685.0   12917.0   
2     2014    53  20447732  115087.0  147287.0  176065.0  143105.0  202069.0   
3     2014    53  20443951   20900.0   24420.0   27068.0   20460.0   25580.0   
4     2014    53  20443944    4430.0    5864.0    3310.0    1853.0    2836.0   
5     2014    53  20443943   57289.0   80036.0  112511.0  116002.0  171900.0   
6     2014    53  20443941   21868.0   30620.0   45886.0   49732.0   75195.0   
7     2014    53  20443902   41105.0   57637.0   54540.0   68171.0   64825.0   
8     2014    53  20443901   39381.0   56933.0   59899.0   67243.0   58880.0   
9     2014    53  20443308    5922.0   16070.0   14665.0   10640.0   20150.0   
10    2014    53  20443307    5120.0    9280.0    9015.0    7030.0   12500.0   
11    2014    53  20443057   52035.0   64435.0   63748.0   56720.0   57467.0   
12    2014    53  20443056  260820.0  313213.0  309797.0  288670.0  308410.0   
13    2014    53  20443055   39965.0   52095.0   45319.0   38690.0   45600.0   
14    2014    53  20447919    1390.0    1330.0    2038.0    1690.0    1830.0   
15    2014    53  20447972  151240.0  205018.0  222380.0  211780.0  191280.0   
16    2014    53  20447973   90680.0  121015.0  136680.0  141805.0  142980.0   
17    2014    53  20448083  349524.0  427399.0  447686.0  440211.0  420113.0   
18    2014    53  20448084  356664.0  434893.0  456498.0  436458.0  406676.0   
19    2014    53  20448086    1610.0    1980.0    2500.0    1710.0    2285.0   
20    2014    53  20448095   96366.0  124304.0  126985.0  117356.0  134970.0   
21    2014    53  20448162   49250.0   72969.0   63869.0   60120.0   68902.0   
22    2014    53  20448312     860.0     880.0    1070.0     740.0     900.0   
23    2014    53  20448455   11546.0   15598.0   15334.0   12456.0   16454.0   
24    2014    53  20448467    6473.0    7353.0    9471.0    9078.0    8343.0   
25    2014    53  20448805  110907.0  143261.0  141189.0  135794.0  127524.0   
26    2014    53  20448900    5620.0    9982.0   10559.0    8252.0    9000.0   
27    2014    53  20448958   35225.0   64345.0   77183.0   98850.0  156492.0   
28    2014    53  20441997    9695.0   13490.0   12850.0   11090.0   14823.0   
29    2014    53  20441382   13490.0   19755.0   17685.0   16420.0   16990.0   
...    ...   ...       ...       ...       ...       ...       ...       ...   
1986  2015     4  20441131    9190.0   10080.0   10215.0   10725.0    9335.0   
1987  2015     4  20441187  211593.0  228546.0  227395.0  280857.0  185920.0   
1988  2015     4  20441372   10990.0   10580.0    9255.0   10651.0    8860.0   
1989  2015     4  20438683   23590.0   20395.0   19040.0   23210.0   20915.0   
1990  2015     4  20438923    2360.0    2040.0    2540.0    2360.0    2380.0   
1991  2015     4  20438941     565.0     890.0     815.0    1030.0     825.0   
1992  2015     4  20438686   15500.0   14785.0   14760.0   16777.0   14200.0   
1993  2015     4  20438690     430.0     595.0     615.0     540.0     220.0   
1994  2015     4  20438691     100.0      40.0      70.0     100.0      50.0   
1995  2015     4  20438693  101345.0  101553.0  107065.0  100670.0   94716.0   
1996  2015     4  20438694  597449.0  587464.0  586763.0  597044.0  559143.0   
1997  2015     4  20438702  266010.0  240524.0  253241.0  267775.0  242234.0   
1998  2015     4  20438703  574490.0  497758.0  544345.0  541795.0  515546.0   
1999  2015     4  20438704   21319.0   21825.0   21803.0   22410.0   18760.0   
2000  2015     4  20438705    6805.0    6330.0    5870.0    5310.0    4460.0   
2001  2015     4  20438706   24840.0   26430.0   25860.0   26995.0   26296.0   
2002  2015     4  20438710  457442.0  409176.0  434183.0  445360.0  415486.0   
2003  2015     4  20438711  106051.0  114452.0   99345.0  109489.0   99031.0   
2004  

In [171]:
preds = SUPER_HYDRA_NAGIBATOR_1337_POCAN.predict(test)

In [172]:
sample_submission['y'] = preds

In [173]:
sample_submission.to_csv("Malyshev_shnp.tsv", sep=',', index=False)

In [182]:
X_CONTROL = merged_table.drop(['y'], axis=1)[20000:]
Y_CONTROL = merged_table['y'][20000:]

smape100(SUPER_HYDRA_NAGIBATOR_1337_POCAN, X_CONTROL, Y_CONTROL)

7.7408415890234359

In [176]:
%%time

#Whole sample

X = d.drop(['y'], axis=1)
Y = d['y']
result = ms.cross_val_score(estimator41, X, Y, scoring=smape_score)
print result.mean()

0.310650467921
CPU times: user 7min 42s, sys: 9.02 s, total: 7min 51s
Wall time: 4min 11s


In [37]:
ms.cross_val_score(model, X, Y, scoring=smape_score)

array([ 0.41010236,  0.40813405,  0.41178169])

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
def try_estimator(estimator, name='NA'):
    result = ms.cross_val_score(estimator, X, Y, scoring=smape_score)
    results.append([name, result.mean()])
    print (name, result.mean())
    return result.mean()

In [40]:
lr = LinearRegression()
try_estimator(estimator=lr, name='Linear Regression')

('Linear Regression', 0.53406203387848594)


/usr/local/lib/python2.7/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


0.53406203387848594

In [41]:
try_estimator(GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=43), name='GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=43)')

('GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=43)', 0.41000603410880498)


0.41000603410880498

In [42]:
try_estimator(GradientBoostingRegressor(n_estimators=500, max_depth=4, random_state=43), name='GradientBoostingRegressor(n_estimators=500, max_depth=4, random_state=43)')

('GradientBoostingRegressor(n_estimators=500, max_depth=4, random_state=43)', 0.39822846048346211)


0.39822846048346211

In [44]:
try_estimator(GradientBoostingRegressor(n_estimators=1000, max_depth=8, random_state=43, learning_rate=0.1))

('NA', 0.32999022230159347)


0.32999022230159347

In [ ]:
param = {'max_depth':2, 'eta':1, 'silent':1, 'objective':'binary:logistic' }
num_round = 2
bst = xgb.train(param, X, num_round)
# make prediction
preds = bst.predict(Y)


In [38]:
from xgboost import XGBRegressor

In [47]:
XGB_regressor = XGBRegressor(max_depth=i, learning_rate=0.1, n_estimators=300, nthread=2, seed=41)

In [48]:
%%time
try_estimator(XGB_regressor)

('NA', 0.38776376595074957)
CPU times: user 15.1 s, sys: 876 ms, total: 16 s
Wall time: 8.98 s


0.38776376595074957

In [49]:
res = []
for i in range(20):
    x = try_estimator(XGBRegressor(max_depth=i, learning_rate=0.1, n_estimators=300, nthread=2, seed=41))
    res.append(x)

('NA', 1.3232990596793963)
('NA', 0.58597451775840581)
('NA', 0.47110170598914847)
('NA', 0.43691524482079364)
('NA', 0.40296035768042993)
('NA', 0.38776376595074957)
('NA', 0.36532488023136195)
('NA', 0.34575241431765291)
('NA', 0.33468757657608811)
('NA', 0.32089281796958707)
('NA', 0.31754439894833175)
('NA', 0.30835939783371691)
('NA', 0.30444753426342591)
('NA', 0.30067414216571142)
('NA', 0.30104561552272702)
('NA', 0.30031674835677263)
('NA', 0.29842397806566257)
('NA', 0.29576202552064507)
('NA', 0.29711285135991827)
('NA', 0.29656682576474547)


In [50]:
%%time
lr_grid = np.arange(0.05, 0.4, 0.03)
res_by_lr = []
for lr in lr_grid:
    x = try_estimator(XGBRegressor(max_depth=16, learning_rate=lr, n_estimators=300, nthread=2, seed=41))
    print(lr, res_by_lr.append(x))

('NA', 0.29572950487617811)
(0.050000000000000003, None)
('NA', 0.29697389716018585)
(0.080000000000000002, None)
('NA', 0.29939204223376087)
(0.11, None)
('NA', 0.30008623416189462)
(0.14000000000000001, None)
('NA', 0.30131995633373537)
(0.16999999999999998, None)
('NA', 0.30155147687989453)
(0.20000000000000001, None)
('NA', 0.30379828589037694)
(0.22999999999999998, None)
('NA', 0.30461529712720031)
(0.26000000000000001, None)
('NA', 0.31094701607890923)
(0.28999999999999998, None)
('NA', 0.30918148865731715)
(0.32000000000000001, None)
('NA', 0.3129327586913393)
(0.34999999999999998, None)


KeyboardInterrupt: 

In [51]:
%%time
lr_grid = np.arange(0.01, 0.2, 0.01)
res_by_lr2 = []
for lr in lr_grid:
    print(lr)
    x = try_estimator(XGBRegressor(max_depth=13, learning_rate=lr, n_estimators=300, nthread=2, seed=41))
    res_by_lr2.append(x)

0.01
('NA', 0.29391462017201536)
0.02
('NA', 0.29591141411096433)
0.03
('NA', 0.29734314603636919)
0.04
('NA', 0.29676734601825178)
0.05
('NA', 0.29806353078899034)
0.06


KeyboardInterrupt: 

In [53]:
%%time
n_grid = np.arange(100, 1000, 100)
res_by_n_grid = []
for n in n_grid:
    print(n)
    x = try_estimator(XGBRegressor(max_depth=13, learning_rate=0.1, n_estimators=n, nthread=2, seed=41))
    res_by_n_grid.append(x)

100
('NA', 0.30113647453782377)
200
('NA', 0.30007189959073982)
300
('NA', 0.30067414216571142)
400
('NA', 0.30169827686312384)
500
('NA', 0.30192616075098822)
600
('NA', 0.30197754247488845)
700
('NA', 0.30197956729417313)
800
('NA', 0.30198649183716775)
900
('NA', 0.30198518859581686)
CPU times: user 11min 21s, sys: 56.1 s, total: 12min 17s
Wall time: 7min 15s


In [54]:
try_estimator(XGBRegressor(max_depth=16, learning_rate=0.05, n_estimators=200, nthread=2, seed=41))

('NA', 0.29496316658362326)


0.29496316658362326

In [57]:
X_full = train.drop(['Num','y'], axis=1)
Y_full = train['y']

In [58]:
ms.cross_val_score(XGBRegressor(max_depth=16, learning_rate=0.05, n_estimators=200, nthread=2, seed=41), X_full, Y_full).mean()

0.947928723563221

In [37]:
from statsmodels.sandbox.stats.multicomp import multipletests
import scipy.stats as sps

In [14]:
correlation_matrix = [[sps.spearmanr(train['f'+str(i)], train['f'+str(j)]) for i in range(1, 31)] for j in range(1, 31)]

In [15]:
correlations = np.array([np.array(list(map(lambda x: x[0], row))) for row in correlation_matrix])

In [16]:
from collections import Counter

In [46]:
def metric(x, y):
    return 2 * np.sum(np.abs(x - y) / (np.abs(x) + np.abs(y))) / x.shape[0]

In [18]:
frac = 0.1 # fraction of learning examples used for model fitting

# sample the train set if your don't want to deel with all examples
train_sample = train.sample(frac=frac, random_state=42)

X = train_sample.drop(['Num','y'], axis=1)
y = train_sample['y']
print len(X), len(y)

7246 7246


In [19]:
[metric(np.array(train['y']), np.array(train['f'+str(i)])) for i in range(1, 31)]

[0.67966203632457223,
 0.66543009085481197,
 0.67235004065953241,
 0.67808306484768888,
 0.66759252471595798,
 0.6601773832467851,
 0.66030987066944602,
 0.66895090372888877,
 0.66168126033550467,
 0.65118094526235804,
 0.64533790598528062,
 0.65402923114688261,
 0.65129311035438453,
 0.64023570995415779,
 0.63084288757875384,
 0.63410324812514962,
 0.63727111505518719,
 0.62545466647385006,
 0.61447120959737445,
 0.60822138613484145,
 0.61623022407407235,
 0.60418060727787248,
 0.59346195253320611,
 0.58148326558485497,
 0.58930479460132901,
 0.58370856317466835,
 0.57128992341085938,
 0.55870235470289276,
 0.55958293988778751,
 0.56325502364433522]

In [20]:
%%time
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=43)
model.fit(X, y)

# preds = model.predict(test.drop(['Num'], axis=1))

# print len(preds)
# print len(sample_submission)

CPU times: user 6.82 s, sys: 97.8 ms, total: 6.92 s
Wall time: 7.19 s


In [47]:
def smape_score(estimator, X, y):
    return metric(estimator.predict(X), y)

In [36]:
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor

In [23]:
rfestimator = RandomForestRegressor(max_depth=5, random_state=41)

In [24]:
ms.cross_val_score(model, X, y, scoring=smape_score)

array([ 0.43522116,  0.41562327,  0.41814903])

In [25]:
ms.cross_val_score(rfestimator, X, y, scoring=smape_score)

array([ 0.46393184,  0.48749146,  0.51795154])

In [26]:
etestimator = ExtraTreesRegressor(max_depth=4, random_state=41)
ms.cross_val_score(etestimator, X, y, scoring=smape_score)

array([ 0.60504401,  0.6077744 ,  0.63275096])